# import

In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

sns.set_theme()

# jupyter notebook full-width display
# doesn't seem to work in Edge
from IPython.core.display import display, HTML
display(HTML(""))

# pandas formatting
pd.set_option('display.float_format', '{:.3f}'.format)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

In [76]:
df_raw = pd.read_csv('csv_MASTER_Gaspereau_details_Larry.csv')

C:\Users\CARRK\AppData\Local\Temp\2\ipykernel_6992\2472411369.py:1: DtypeWarning: Columns (9,14,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv('csv_MASTER_Gaspereau_details_Larry.csv')


In [38]:
df_raw.dtypes

YEAR                  int64
MM                    int64
DD                    int64
WEEK                float64
SITE                 object
PERIOD               object
CONDITION            object
FISH_NO               int64
FL_WET              float64
FL_FROZEN            object
FL_STD              float64
WEIGHT              float64
SPECIES              object
SEX                  object
MATURITY             object
GONAD_WEIGHT         object
1st Person Aging     object
AGE                  object
FSP                  object
Comments             object
2nd Person Aging     object
AGE.1                object
FSP.1                object
Comments.1           object
Envelop Comments     object
dtype: object

In [39]:
df_raw.describe(include='all').T

count unique                                   top  \
YEAR             35619.000    NaN                                   NaN   
MM               35619.000    NaN                                   NaN   
DD               35619.000    NaN                                   NaN   
WEEK             22371.000    NaN                                   NaN   
SITE                 35501     78                                    12   
PERIOD               30417      4                                    AM   
CONDITION            35424      4                                Frozen   
FISH_NO          35619.000    NaN                                   NaN   
FL_WET            9660.000    NaN                                   NaN   
FL_FROZEN            25496    235                                   250   
FL_STD           35245.000    NaN                                   NaN   
WEIGHT           35318.000    NaN                                   NaN   
SPECIES              35392      3                                     A   
SEX                  35392      4                                     F   
MATURITY             34996     14                                     4   
GONAD_WEIGHT         17285    817                                    41   
1st Person Aging      7118      1                                    JM   
AGE                  31568     24                                     3   
FSP                  31350     26                                     3   
Comments              1885    856                                 NICE    
2nd Person Aging       390      1                                    LF   
AGE.1                  390      7                                     3   
FSP.1                  390      5                                     3   
Comments.1              22     17                           poor scales   
Envelop Comments       625     73  parasites; round worms, less than 5.   

                   freq     mean    std      min      25%      50%      75%  \
YEAR                NaN 2000.901 11.021 1983.000 1990.000 2000.000 2011.000   
MM                  NaN    5.392  0.500    4.000    5.000    5.000    6.000   
DD                  NaN   16.121  8.768    1.000    9.000   16.000   24.000   
WEEK                NaN    5.050  2.005    1.000    4.000    5.000    6.000   
SITE               6668      NaN    NaN      NaN      NaN      NaN      NaN   
PERIOD            16222      NaN    NaN      NaN      NaN      NaN      NaN   
CONDITION         24940      NaN    NaN      NaN      NaN      NaN      NaN   
FISH_NO             NaN   17.770 11.672    1.000    9.000   17.000   25.000   
FL_WET              NaN  253.376 20.107    1.000  240.000  253.000  267.000   
FL_FROZEN           990      NaN    NaN      NaN      NaN      NaN      NaN   
FL_STD              NaN  253.169 27.956   20.000  241.000  254.000  268.000   
WEIGHT              NaN  217.944 61.426   15.100  174.300  211.200  255.100   
SPECIES           30885      NaN    NaN      NaN      NaN      NaN      NaN   
SEX               17621      NaN    NaN      NaN      NaN      NaN      NaN   
MATURITY          26149      NaN    NaN      NaN      NaN      NaN      NaN   
GONAD_WEIGHT         93      NaN    NaN      NaN      NaN      NaN      NaN   
1st Person Aging   7118      NaN    NaN      NaN      NaN      NaN      NaN   
AGE               12903      NaN    NaN      NaN      NaN      NaN      NaN   
FSP               20329      NaN    NaN      NaN      NaN      NaN      NaN   
Comments            233      NaN    NaN      NaN      NaN      NaN      NaN   
2nd Person Aging    390      NaN    NaN      NaN      NaN      NaN      NaN   
AGE.1               166      NaN    NaN      NaN      NaN      NaN      NaN   
FSP.1               279      NaN    NaN      NaN      NaN      NaN      NaN   
Comments.1            5      NaN    NaN      NaN      NaN      NaN      NaN   
Envelop Comments    187      NaN    NaN      NaN      NaN      NaN      NaN   

               

In [40]:
df_raw.YEAR.unique()

array([1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019], dtype=int64)

In [42]:
df_raw.isnull().describe().T

count unique    top   freq
YEAR              35619      1  False  35619
MM                35619      1  False  35619
DD                35619      1  False  35619
WEEK              35619      2  False  22371
SITE              35619      2  False  35501
PERIOD            35619      2  False  30417
CONDITION         35619      2  False  35424
FISH_NO           35619      1  False  35619
FL_WET            35619      2   True  25959
FL_FROZEN         35619      2  False  25496
FL_STD            35619      2  False  35245
WEIGHT            35619      2  False  35318
SPECIES           35619      2  False  35392
SEX               35619      2  False  35392
MATURITY          35619      2  False  34996
GONAD_WEIGHT      35619      2   True  18334
1st Person Aging  35619      2   True  28501
AGE               35619      2  False  31568
FSP               35619      2  False  31350
Comments          35619      2   True  33734
2nd Person Aging  35619      2   True  35229
AGE.1             35619      2   True  35229
FSP.1             35619      2   True  35229
Comments.1        35619      2   True  35597
Envelop Comments  35619      2   True  34994

In [78]:
df_raw.FL_STD.unique()

array([285.    , 288.    , 280.    , 286.    , 297.    , 271.    ,
       277.    , 276.    , 279.    , 253.    , 299.    , 293.    ,
       251.    , 247.    , 287.    , 264.    , 270.    , 268.    ,
       255.    , 274.    , 269.    , 309.    , 275.    , 258.    ,
       257.    , 282.    , 259.    , 265.    , 290.    , 278.    ,
       305.    , 248.    , 252.    , 272.    , 308.    , 283.    ,
       273.    , 289.    , 294.    , 260.    , 263.    , 266.    ,
       254.    , 244.    , 281.    , 256.    , 261.    , 245.    ,
       250.    , 295.    , 262.    , 246.    , 249.    , 240.    ,
       233.    , 291.    , 238.    , 235.    , 242.    , 243.    ,
       232.    , 239.    , 241.    , 237.    , 227.    , 222.    ,
       267.    , 236.    , 292.    , 302.    , 314.    , 315.    ,
       298.    , 307.    , 303.    , 296.    , 312.    , 300.    ,
       325.    , 318.    , 304.    , 310.    , 301.    , 319.    ,
       324.    , 331.    , 230.    , 231.    , 234.    , 228. 

In [81]:
df_raw.WEIGHT.unique()

array([336. , 334. , 364. , ..., 105.8,  97.8,  91.2])

# better import

In [107]:
dtypes = {
    'YEAR': 'Int32', 
    'MM': 'Int32', 
    'DD': 'Int32', 
    'WEEK': 'Int32', 
    'SITE': 'object', 
    'PERIOD': 'object', 
    'CONDITION': 'object', 
    'FISH_NO': 'Int32', 
    'FL_WET': 'Int32', 
#     'FL_FROZEN': 'Int32',  # error: Unable to parse string " "
    'FL_STD': 'float64',  # error: cannot safely cast non-equivalent float64 to int32
    'WEIGHT': 'float64',  # error: cannot safely cast non-equivalent float64 to int32
    'SPECIES': 'object', 
    'SEX': 'object', 
#     'MATURITY': 'Int32',  # error: Unable to parse string " "
#     'GONAD_WEIGHT': 'float64',  # error: Unable to parse string " "
    '1st Person Aging': 'object',  # error: could not convert string to float: ''
#     'AGE': 'Int32',  # error: Unable to parse string "No Slide"
#     'FSP': 'Int32',  # error: Unable to parse string " "
    'Comments': 'object', 
    '2nd Person Aging': 'object', 
#     'AGE.1': 'Int32',  # error: Unable to parse string "."
#     'FSP.1': 'Int32',  # error: Unable to parse string "." at position 28241
    'Comments.1': 'object', 
    'Envelop Comments': 'object'
} 

df_better = pd.read_csv('csv_MASTER_Gaspereau_details_Larry.csv', dtype=dtypes)

C:\Users\CARRK\AppData\Local\Temp\2\ipykernel_6992\3872033392.py:29: DtypeWarning: Columns (9,14,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_better = pd.read_csv('csv_MASTER_Gaspereau_details_Larry.csv', dtype=dtypes)


# helper functions

In [223]:
def types_of_data(series):
    
    numbers, strings, blanks, n_null = 0, 0, 0, 0
    
    for item in series:
        try:
            float(item)
            if pd.isnull(item):
                n_null += 1
            else:
                numbers += 1
        except:
            strings += 1
            if str(item) == ' ' or str(item) == '':
                blanks += 1
                
    # note: blanks are strings
    return numbers, strings, blanks, n_null


def print_data_info(series):
    
    numbers, strings, blanks, n_null = types_of_data(series)
    
    print('UNIQUE numbers, strings, blanks, null =', types_of_data(series.unique()))
    print('number of numeric =', numbers)
    print('number of strings =', strings)
    print('number of blanks =', blanks)  # blanks are strings
    print('number of null = ', n_null)
    print('check: ', numbers + strings + n_null, '==', series.shape[0])


# test
# types_of_data(df_better.GONAD_WEIGHT.unique())
# types_of_data(df_better.GONAD_WEIGHT)
print_data_info(df_better.GONAD_WEIGHT)

UNIQUE numbers, strings, blanks, null = (816, 1, 1, 1)
number of numeric = 17282
number of strings = 3
number of blanks = 3
number of null =  18334
check:  35619 == 35619


In [218]:
# test
pd.DataFrame(pd.to_numeric(list(df_better.GONAD_WEIGHT.unique()), errors='coerce')).describe()

0
count 816.000
mean   45.151
std    42.704
min     0.000
25%    22.275
50%    41.850
75%    62.225
max   766.000

In [219]:
df_better.GONAD_WEIGHT.unique()

array([nan, '29.6', '50.5', '53.3', '46.1', '66.1', '94.5', '47.7',
       '47.6', '44', '54.9', '26.6', '42.2', '64.2', '40.8', '48.3',
       '56.7', '40.9', '48.2', '34.8', '30.5', '51.8', '41.8', '35.9',
       '40', '36.8', '53.9', '38.2', '46.9', '48.7', '85.9', '40.5', '51',
       '62.2', '42.3', '43.6', '46.5', '43.5', '40.3', '59.6', '31.2',
       '31.3', '52.6', '43.9', '48.5', '77.8', '43.8', '37.1', '43.1',
       '51.5', '32.4', '52.3', '44.9', '65.8', '50.3', '54.5', '37.9',
       '55.3', '51.3', '29.7', '20.9', '81.2', '47.3', '58', '35.5',
       '51.1', '53.4', '58.3', '43.3', '27.5', '45.1', '39.5', '52.5',
       '34.6', '19.1', '46.2', '65.6', '52.4', '49', '45.3', '47.2',
       '54.7', '51.7', '41.4', '55.9', '47.1', '48.9', '55.7', '50.4',
       '61.7', '49.2', '53.6', '41.5', '30.6', '25.2', '56.9', '35',
       '22.7', '32', '13.2', '42.4', '39.3', '33.5', '39.6', '48.8',
       '76.8', '16.9', '32.7', '18', '56.1', '44.5', '35.4', '68.5',
       '41.1', '5

In [194]:
def types_of_data(series):
    numbers, strings, blanks = 0, 0, 0
    for item in list(series.unique()):
        try:
            float(item)
            numbers += 1
        except:
            if str(item) == ' ' or str(item) == '':
                blanks += 1
            elif pd.isnull(item):
                pass
            else:
                strings += 1
    return numbers, strings, blanks


def how_many_numeric(series):
    numbers = 0
    for item in series:
        try:
            float(item)
            if pd.isnull(item):
                pass
            else:
                numbers += 1
        except:
            pass
    return numbers


def how_many_strings(series):
    strings = 0
    for item in series:
        try:
            float(item)
        except:
            if pd.isnull(item):
                pass
            else:
                strings += 1
    return numbers


def how_many_blanks(series):
    return series[(series == ' ') | (series == '')].shape[0]


def print_data_info(series):
    n_numeric = how_many_numeric(series)
    n_string = how_many_strings(series)
    n_null = series.isnull().sum()
    
    print('UNIQUE numbers, strings, blanks =', types_of_data(series))
    print('number of numeric =', n_numeric)
    print('number of strings =', n_string)
    print('number of blanks =', how_many_blanks(series))  # blanks are strings
    print('number of null = ', n_null)
    print('check: ', n_numeric + n_string + n_null, '==', series.shape[0])

In [195]:
print_data_info(df_better.GONAD_WEIGHT)

UNIQUE numbers, strings, blanks = (817, 0, 1)
number of numeric = 17282
number of strings = 817
number of blanks = 3
number of null =  18334
check:  36433 == 35619


### FL_FROZEN

In [108]:
# should be able to convert to numeric and coerce errors
df_better.FL_FROZEN.unique()

array([nan, '275', '250', '240', '245', '272', '260', '262', '265', '300',
       '280', '285', '270', '263', '252', '279', '255', '258', '246',
       '277', '271', '251', '244', '268', '266', '264', '274', '267',
       '236', '239', '273', '248', '253', '284', '290', '257', '293',
       '305', '282', '256', '276', '254', '306', '283', '278', '286',
       '289', '288', '296', '298', '234', '294', '269', '287', '303',
       '247', '291', '316', '261', '242', '237', '309', '295', '301',
       '241', '281', '249', '292', '238', '259', '230', '243', '235',
       '310', '315', '233', '322', '232', '231', '228', '222', '225',
       '223', '226', '229', '227', '224', '220', '221', '212', '145',
       '157', '151', '155', '161', '166', '147', '150', '217', '160',
       '320', '317', '218', '215', '219', '207', '213', '210', '208',
       '190', '200', '308', '175', '148', '304', '216', '214', '211',
       '209', '118', '204', '205', '199', '203', '206', '299', '202',
       '197', '

In [173]:
print_data_info(df_better.FL_FROZEN)

UNIQUE numbers, strings, blanks = (235, 0, 1)
number of numeric = 25496
number of blanks = 1
number of null =  10123


### MATURITY
* CONFIRM: either convert 44 to null or make it 4
* CONFIRM: either convert 3? to null or make it 3
* all ' ' to null

In [118]:
# may need to ask an expert how to convert these values
## 44 looks wrong, should 3? be 3 or null
## ' ' could be coerced into an error
df_better.MATURITY.unique()

array(['2', '1', '3', '0', '4', nan, '6', '5', ' ', '3?', 4.0, 3.0, 44.0,
       2.0, 5.0], dtype=object)

In [120]:
# only 1 row has maturity == 44, should very likely be a 4
df_better[df_better.MATURITY == 44]

YEAR  MM  DD  WEEK SITE PERIOD CONDITION  FISH_NO  FL_WET FL_FROZEN  \
34619  2019   5  15     3   26     AM    FROZEN       25    <NA>   241.000   

       FL_STD  WEIGHT SPECIES SEX MATURITY GONAD_WEIGHT 1st Person Aging AGE  \
34619 249.003 200.900       A   F   44.000         27.1               JM   4   

      FSP Comments 2nd Person Aging AGE.1 FSP.1 Comments.1 Envelop Comments  
34619   3      NaN              NaN   NaN   NaN        NaN              NaN

In [174]:
print_data_info(df_better.MATURITY)

UNIQUE numbers, strings, blanks = (13, 1, 1)
number of numeric = 34996
number of blanks = 1
number of null =  623


### GONAD_WEIGHT
* convert ' ' to Null

In [125]:
pd.to_numeric(df_better.GONAD_WEIGHT, errors='coerce').describe()

count   17282.000
mean       37.250
std        16.292
min         0.000
25%        27.400
50%        36.100
75%        46.200
max       766.000
Name: GONAD_WEIGHT, dtype: float64

In [132]:
# many null gonads, seems to convert to numeric correctly
df_better[df_better.GONAD_WEIGHT.isnull()].shape

(18334, 25)

In [175]:
print_data_info(df_raw.GONAD_WEIGHT)

UNIQUE numbers, strings, blanks = (817, 0, 1)
number of numeric = 17285
number of blanks = 3
number of null =  18334


### AGE

In [177]:
print_data_info(df_raw.AGE)

UNIQUE numbers, strings, blanks = (12, 13, 0)
number of numeric = 31568
number of blanks = 0
number of null =  4051


### FSP

In [178]:
print_data_info(df_raw.FSP)

UNIQUE numbers, strings, blanks = (11, 15, 1)
number of numeric = 31350
number of blanks = 1
number of null =  4269


### AGE.1

In [180]:
print_data_info(df_raw['AGE.1'])

UNIQUE numbers, strings, blanks = (7, 1, 0)
number of numeric = 390
number of blanks = 0
number of null =  35229


### FSP.1

In [181]:
print_data_info(df_raw['FSP.1'])

UNIQUE numbers, strings, blanks = (5, 1, 0)
number of numeric = 390
number of blanks = 0
number of null =  35229
